import { PremblyBaseResponse, PremblyRequestPayload } from '../common.interface';

export type NigeriaDataVerificationServiceAccountWithNameComparismRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceAccountWithNameComparismResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceAddressVerificationRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceAddressVerificationResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceAddressVerificationStatusRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceAddressVerificationStatusResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceAdvanceCacRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceAdvanceCacResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceAdvanceDriversLicenseRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceAdvanceDriversLicenseResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceAdvancePhoneNumberRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceAdvancePhoneNumberResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceBankAccountBasicRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceBankAccountBasicResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceBasicCacRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceBasicCacResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceBasicPhoneNumberRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceBasicPhoneNumberResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceBusinessAddressVerificationRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceBusinessAddressVerificationResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceBvnAdvanceRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceBvnAdvanceResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceBvnBasicRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceBvnBasicResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceBvnPlusFaceValidationRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceBvnPlusFaceValidationResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceCreditBureauCommercialBusinessBasicRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceCreditBureauCommercialBusinessBasicResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceCreditBureauConsumerIndividualBasicRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceCreditBureauConsumerIndividualBasicResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceCreditBureauCommercialBusinessAdvanceRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceCreditBureauCommercialBusinessAdvanceResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceCreditBureauConsumerIndividualAdvanceRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceCreditBureauConsumerIndividualAdvanceResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceDriversLicensePlusFaceValidationRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceDriversLicensePlusFaceValidationResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceDriversLicenseImageRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceDriversLicenseImageResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceDriversLicenseV2Request = PremblyRequestPayload;
export type NigeriaDataVerificationServiceDriversLicenseV2Response = PremblyBaseResponse;

export type NigeriaDataVerificationServiceGetBvnWithPhoneNumberRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceGetBvnWithPhoneNumberResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceGetTinWithPhoneNumberRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceGetTinWithPhoneNumberResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceFinancialAccountsAdvanceRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceFinancialAccountsAdvanceResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceInsurancePolicyRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceInsurancePolicyResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceInternationalPassportRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceInternationalPassportResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceInternationalPassportPlusFaceValidationRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceInternationalPassportPlusFaceValidationResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceInternationalPassportImageRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceInternationalPassportImageResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceListBankCodeRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceListBankCodeResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceNinBasicRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceNinBasicResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceNinNinauthLevel2Request = PremblyRequestPayload;
export type NigeriaDataVerificationServiceNinNinauthLevel2Response = PremblyBaseResponse;

export type NigeriaDataVerificationServiceNinWithFaceRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceNinWithFaceResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceNinAdvanceRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceNinAdvanceResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServicePassportVersion2Request = PremblyRequestPayload;
export type NigeriaDataVerificationServicePassportVersion2Response = PremblyBaseResponse;

export type NigeriaDataVerificationServicePlateNumberVerificationRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServicePlateNumberVerificationResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceStampDutyRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceStampDutyResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceTaxIdentificationNumberTinRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceTaxIdentificationNumberTinResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceVotersCardRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceVotersCardResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceWaecVerificationRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceWaecVerificationResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceScumlRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceScumlResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceTccCheckerRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceTccCheckerResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceMetreNumberRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceMetreNumberResponse = PremblyBaseResponse;

export type NigeriaDataVerificationServiceNyscRequest = PremblyRequestPayload;
export type NigeriaDataVerificationServiceNyscResponse = PremblyBaseResponse;

