import { PremblyModuleOptions } from '../../interfaces';
import { BrazilDataVerificationService } from './brazil.service';
import { CanadaDataVerificationService } from './canada.service';
import { ChinaDataVerificationService } from './china.service';
import { CoteDivoireDataVerificationService } from './cote-divoire.service';
import { CyprusDataVerificationService } from './cyprus.service';
import { CzechRepublicDataVerificationService } from './czech-republic.service';
import { GambiaDataVerificationService } from './gambia.service';
import { GhanaDataVerificationService } from './ghana.service';
import { GermanyDataVerificationService } from './germany.service';
import { GreeceDataVerificationService } from './greece.service';
import { HongKongDataVerificationService } from './hong-kong.service';
import { IndiaDataVerificationService } from './india.service';
import { IndonesiaDataVerificationService } from './indonesia.service';
import { JapanDataVerificationService } from './japan.service';
import { KenyaDataVerificationService } from './kenya.service';
import { KoreaDataVerificationService } from './korea.service';
import { LiberiaDataVerificationService } from './liberia.service';
import { MalawiDataVerificationService } from './malawi.service';
import { MalaysiaDataVerificationService } from './malaysia.service';
import { MaltaDataVerificationService } from './malta.service';
import { MexicoDataVerificationService } from './mexico.service';
import { NetherlandsDataVerificationService } from './netherlands.service';
import { NewZealandDataVerificationService } from './new-zealand.service';
import { NigeriaDataVerificationService } from './nigeria.service';
import { PortugalDataVerificationService } from './portugal.service';
import { RwandaDataVerificationService } from './rwanda.service';
import { SierraLeoneDataVerificationService } from './sierra-leone.service';
import { SingaporeDataVerificationService } from './singapore.service';
import { SouthAfricaDataVerificationService } from './south-africa.service';
import { SwitzerlandDataVerificationService } from './switzerland.service';
import { TaiwanDataVerificationService } from './taiwan.service';
import { TanzaniaDataVerificationService } from './tanzania.service';
import { ThailandDataVerificationService } from './thailand.service';
import { UgandaDataVerificationService } from './uganda.service';
import { UnitedKingdomDataVerificationService } from './united-kingdom.service';
import { UnitedStatesOfAmericaDataVerificationService } from './united-states-of-america.service';
import { VietnamDataVerificationService } from './vietnam.service';
import { ZambiaDataVerificationService } from './zambia.service';
import { ZimbabweDataVerificationService } from './zimbabwe.service';

export class DataVerificationService {
  public readonly brazil: BrazilDataVerificationService;
  public readonly canada: CanadaDataVerificationService;
  public readonly china: ChinaDataVerificationService;
  public readonly coteDIvoire: CoteDivoireDataVerificationService;
  public readonly cyprus: CyprusDataVerificationService;
  public readonly czechRepublic: CzechRepublicDataVerificationService;
  public readonly gambia: GambiaDataVerificationService;
  public readonly ghana: GhanaDataVerificationService;
  public readonly germany: GermanyDataVerificationService;
  public readonly greece: GreeceDataVerificationService;
  public readonly hongKong: HongKongDataVerificationService;
  public readonly india: IndiaDataVerificationService;
  public readonly indonesia: IndonesiaDataVerificationService;
  public readonly japan: JapanDataVerificationService;
  public readonly kenya: KenyaDataVerificationService;
  public readonly korea: KoreaDataVerificationService;
  public readonly liberia: LiberiaDataVerificationService;
  public readonly malawi: MalawiDataVerificationService;
  public readonly malaysia: MalaysiaDataVerificationService;
  public readonly malta: MaltaDataVerificationService;
  public readonly mexico: MexicoDataVerificationService;
  public readonly netherlands: NetherlandsDataVerificationService;
  public readonly newZealand: NewZealandDataVerificationService;
  public readonly nigeria: NigeriaDataVerificationService;
  public readonly portugal: PortugalDataVerificationService;
  public readonly rwanda: RwandaDataVerificationService;
  public readonly sierraLeone: SierraLeoneDataVerificationService;
  public readonly singapore: SingaporeDataVerificationService;
  public readonly southAfrica: SouthAfricaDataVerificationService;
  public readonly switzerland: SwitzerlandDataVerificationService;
  public readonly taiwan: TaiwanDataVerificationService;
  public readonly tanzania: TanzaniaDataVerificationService;
  public readonly thailand: ThailandDataVerificationService;
  public readonly uganda: UgandaDataVerificationService;
  public readonly unitedKingdom: UnitedKingdomDataVerificationService;
  public readonly unitedStatesOfAmerica: UnitedStatesOfAmericaDataVerificationService;
  public readonly vietnam: VietnamDataVerificationService;
  public readonly zambia: ZambiaDataVerificationService;
  public readonly zimbabwe: ZimbabweDataVerificationService;

  constructor(options: PremblyModuleOptions) {
    this.brazil = new BrazilDataVerificationService(options);
    this.canada = new CanadaDataVerificationService(options);
    this.china = new ChinaDataVerificationService(options);
    this.coteDIvoire = new CoteDivoireDataVerificationService(options);
    this.cyprus = new CyprusDataVerificationService(options);
    this.czechRepublic = new CzechRepublicDataVerificationService(options);
    this.gambia = new GambiaDataVerificationService(options);
    this.ghana = new GhanaDataVerificationService(options);
    this.germany = new GermanyDataVerificationService(options);
    this.greece = new GreeceDataVerificationService(options);
    this.hongKong = new HongKongDataVerificationService(options);
    this.india = new IndiaDataVerificationService(options);
    this.indonesia = new IndonesiaDataVerificationService(options);
    this.japan = new JapanDataVerificationService(options);
    this.kenya = new KenyaDataVerificationService(options);
    this.korea = new KoreaDataVerificationService(options);
    this.liberia = new LiberiaDataVerificationService(options);
    this.malawi = new MalawiDataVerificationService(options);
    this.malaysia = new MalaysiaDataVerificationService(options);
    this.malta = new MaltaDataVerificationService(options);
    this.mexico = new MexicoDataVerificationService(options);
    this.netherlands = new NetherlandsDataVerificationService(options);
    this.newZealand = new NewZealandDataVerificationService(options);
    this.nigeria = new NigeriaDataVerificationService(options);
    this.portugal = new PortugalDataVerificationService(options);
    this.rwanda = new RwandaDataVerificationService(options);
    this.sierraLeone = new SierraLeoneDataVerificationService(options);
    this.singapore = new SingaporeDataVerificationService(options);
    this.southAfrica = new SouthAfricaDataVerificationService(options);
    this.switzerland = new SwitzerlandDataVerificationService(options);
    this.taiwan = new TaiwanDataVerificationService(options);
    this.tanzania = new TanzaniaDataVerificationService(options);
    this.thailand = new ThailandDataVerificationService(options);
    this.uganda = new UgandaDataVerificationService(options);
    this.unitedKingdom = new UnitedKingdomDataVerificationService(options);
    this.unitedStatesOfAmerica = new UnitedStatesOfAmericaDataVerificationService(options);
    this.vietnam = new VietnamDataVerificationService(options);
    this.zambia = new ZambiaDataVerificationService(options);
    this.zimbabwe = new ZimbabweDataVerificationService(options);
  }
}
